{% set name = "itslive" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itslive-{{ version }}.tar.gz
  sha256: 75e7b9f60471bb0f0baca39a5be69cc8e84c229ed6020f24262eb1365ecc0062

build:
  entry_points:
    - itslive-export = itslive.cli.export:export
    - itslive-plot = itslive.cli.plot:plot
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry >=0.12
    - pip
  run:
    - python >=3.8,<4.0
    - shapely >=1.8
    - matplotlib-base >=3.5
    - pandas ==1.5.1
    - plotext >=0
    - pyproj >=3.3
    - requests >=2.28.1,<3.0.0
    - rich-click >=1.5
    - s3fs >=2022.3
    - tabulate >=0.9.0
    - xarray >=2022.3
    - zarr >=2.11

test:
  imports:
    - itslive
  commands:
    - pip check
    - itslive-export --help
    - itslive-plot --help
  requires:
    - pip

about:
  home: https://github.com/nasa-jpl/itslive-vortex
  summary: Python client for ITSLIVE gralcier velocity data
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - betolink
    - jhkennedy
